
CC = gcc -Wall

compile:
	$(CC) consumer.c -o consumer
	$(CC) producer.c -o producer
	$(CC) main.c -o main
	

clean:
	rm -f *.o
	rm -f *.a
	rm -f *.out
	rm -f consumer
	rm -f producer
	rm -f main
	
run:
	./main


