
CC = gcc -Wall

compile:
	$(CC) main.c -o main
	$(CC) cook.c -o cook
	$(CC) deliverer.c -o deliverer
	

run:
	./main

clean:
	rm -f *.o
	rm -f *.a
	rm -f *.out
	rm -f main
	rm -f cook
	rm -f deliverer
	


